spring:
  config:
    fail-fast: true
    retry:
      max-attempts: 10
      initial-interval: 3000
      multiplier: 1.5
  data:
    mongodb:
      uri: mongodb://mongodb:27017/customers
server:
  port: 8100