spring:
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 3000
        multiplier: 1.5
  datasource:
    url: jdbc:postgresql://postgres:5432/orders
    username: postgres
    password: 5607
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  Kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:org.microservice.orderservice.service.kafka.OrderConfirmation
server:
  port: 8300

application:
  config:
    customer-url: http://customer:customer-service/api/v1/customers
    product-url: http://product:product-service/api/v1/products
    payment-url: http://payment:payment-service/api/v1/payments
